FROM python:3.9-bullseye

WORKDIR /opt/ml/code

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

COPY train.py ./train.py
ENV SAGEMAKER_PROGRAM train.py

ENTRYPOINT ["/opt/ml/code/train.py"]
